// This file is generated by rust-protobuf 2.25.2. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `common.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_25_2;

#[derive(PartialEq,Clone,Default)]
pub struct EntityPos {
    // message fields
    pub t: EntityType,
    pub entity_id: i32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a EntityPos {
    fn default() -> &'a EntityPos {
        <EntityPos as ::protobuf::Message>::default_instance()
    }
}

impl EntityPos {
    pub fn new() -> EntityPos {
        ::std::default::Default::default()
    }

    // .EntityType t = 1;


    pub fn get_t(&self) -> EntityType {
        self.t
    }
    pub fn clear_t(&mut self) {
        self.t = EntityType::T_Null;
    }

    // Param is passed by value, moved
    pub fn set_t(&mut self, v: EntityType) {
        self.t = v;
    }

    // int32 entity_id = 2;


    pub fn get_entity_id(&self) -> i32 {
        self.entity_id
    }
    pub fn clear_entity_id(&mut self) {
        self.entity_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_entity_id(&mut self, v: i32) {
        self.entity_id = v;
    }

    // float x = 3;


    pub fn get_x(&self) -> f32 {
        self.x
    }
    pub fn clear_x(&mut self) {
        self.x = 0.;
    }

    // Param is passed by value, moved
    pub fn set_x(&mut self, v: f32) {
        self.x = v;
    }

    // float y = 4;


    pub fn get_y(&self) -> f32 {
        self.y
    }
    pub fn clear_y(&mut self) {
        self.y = 0.;
    }

    // Param is passed by value, moved
    pub fn set_y(&mut self, v: f32) {
        self.y = v;
    }

    // float z = 5;


    pub fn get_z(&self) -> f32 {
        self.z
    }
    pub fn clear_z(&mut self) {
        self.z = 0.;
    }

    // Param is passed by value, moved
    pub fn set_z(&mut self, v: f32) {
        self.z = v;
    }
}

impl ::protobuf::Message for EntityPos {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.t, 1, &mut self.unknown_fields)?
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.entity_id = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed32 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_float()?;
                    self.x = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed32 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_float()?;
                    self.y = tmp;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed32 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_float()?;
                    self.z = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.t != EntityType::T_Null {
            my_size += ::protobuf::rt::enum_size(1, self.t);
        }
        if self.entity_id != 0 {
            my_size += ::protobuf::rt::value_size(2, self.entity_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.x != 0. {
            my_size += 5;
        }
        if self.y != 0. {
            my_size += 5;
        }
        if self.z != 0. {
            my_size += 5;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.t != EntityType::T_Null {
            os.write_enum(1, ::protobuf::ProtobufEnum::value(&self.t))?;
        }
        if self.entity_id != 0 {
            os.write_int32(2, self.entity_id)?;
        }
        if self.x != 0. {
            os.write_float(3, self.x)?;
        }
        if self.y != 0. {
            os.write_float(4, self.y)?;
        }
        if self.z != 0. {
            os.write_float(5, self.z)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> EntityPos {
        EntityPos::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<EntityType>>(
                "t",
                |m: &EntityPos| { &m.t },
                |m: &mut EntityPos| { &mut m.t },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "entity_id",
                |m: &EntityPos| { &m.entity_id },
                |m: &mut EntityPos| { &mut m.entity_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeFloat>(
                "x",
                |m: &EntityPos| { &m.x },
                |m: &mut EntityPos| { &mut m.x },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeFloat>(
                "y",
                |m: &EntityPos| { &m.y },
                |m: &mut EntityPos| { &mut m.y },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeFloat>(
                "z",
                |m: &EntityPos| { &m.z },
                |m: &mut EntityPos| { &mut m.z },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<EntityPos>(
                "EntityPos",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static EntityPos {
        static instance: ::protobuf::rt::LazyV2<EntityPos> = ::protobuf::rt::LazyV2::INIT;
        instance.get(EntityPos::new)
    }
}

impl ::protobuf::Clear for EntityPos {
    fn clear(&mut self) {
        self.t = EntityType::T_Null;
        self.entity_id = 0;
        self.x = 0.;
        self.y = 0.;
        self.z = 0.;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for EntityPos {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for EntityPos {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct PlayerBasic {
    // message fields
    pub entity_id: u32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a PlayerBasic {
    fn default() -> &'a PlayerBasic {
        <PlayerBasic as ::protobuf::Message>::default_instance()
    }
}

impl PlayerBasic {
    pub fn new() -> PlayerBasic {
        ::std::default::Default::default()
    }

    // uint32 entity_id = 1;


    pub fn get_entity_id(&self) -> u32 {
        self.entity_id
    }
    pub fn clear_entity_id(&mut self) {
        self.entity_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_entity_id(&mut self, v: u32) {
        self.entity_id = v;
    }
}

impl ::protobuf::Message for PlayerBasic {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.entity_id = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.entity_id != 0 {
            my_size += ::protobuf::rt::value_size(1, self.entity_id, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.entity_id != 0 {
            os.write_uint32(1, self.entity_id)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> PlayerBasic {
        PlayerBasic::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "entity_id",
                |m: &PlayerBasic| { &m.entity_id },
                |m: &mut PlayerBasic| { &mut m.entity_id },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<PlayerBasic>(
                "PlayerBasic",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static PlayerBasic {
        static instance: ::protobuf::rt::LazyV2<PlayerBasic> = ::protobuf::rt::LazyV2::INIT;
        instance.get(PlayerBasic::new)
    }
}

impl ::protobuf::Clear for PlayerBasic {
    fn clear(&mut self) {
        self.entity_id = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for PlayerBasic {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PlayerBasic {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ChunkPack {
    // message fields
    pub data: ::std::vec::Vec<u8>,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ChunkPack {
    fn default() -> &'a ChunkPack {
        <ChunkPack as ::protobuf::Message>::default_instance()
    }
}

impl ChunkPack {
    pub fn new() -> ChunkPack {
        ::std::default::Default::default()
    }

    // bytes data = 1;


    pub fn get_data(&self) -> &[u8] {
        &self.data
    }
    pub fn clear_data(&mut self) {
        self.data.clear();
    }

    // Param is passed by value, moved
    pub fn set_data(&mut self, v: ::std::vec::Vec<u8>) {
        self.data = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_data(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.data
    }

    // Take field
    pub fn take_data(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.data, ::std::vec::Vec::new())
    }

    // int32 x = 2;


    pub fn get_x(&self) -> i32 {
        self.x
    }
    pub fn clear_x(&mut self) {
        self.x = 0;
    }

    // Param is passed by value, moved
    pub fn set_x(&mut self, v: i32) {
        self.x = v;
    }

    // int32 y = 3;


    pub fn get_y(&self) -> i32 {
        self.y
    }
    pub fn clear_y(&mut self) {
        self.y = 0;
    }

    // Param is passed by value, moved
    pub fn set_y(&mut self, v: i32) {
        self.y = v;
    }

    // int32 z = 4;


    pub fn get_z(&self) -> i32 {
        self.z
    }
    pub fn clear_z(&mut self) {
        self.z = 0;
    }

    // Param is passed by value, moved
    pub fn set_z(&mut self, v: i32) {
        self.z = v;
    }
}

impl ::protobuf::Message for ChunkPack {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.data)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.x = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.y = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.z = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.data);
        }
        if self.x != 0 {
            my_size += ::protobuf::rt::value_size(2, self.x, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.y != 0 {
            my_size += ::protobuf::rt::value_size(3, self.y, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.z != 0 {
            my_size += ::protobuf::rt::value_size(4, self.z, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.data.is_empty() {
            os.write_bytes(1, &self.data)?;
        }
        if self.x != 0 {
            os.write_int32(2, self.x)?;
        }
        if self.y != 0 {
            os.write_int32(3, self.y)?;
        }
        if self.z != 0 {
            os.write_int32(4, self.z)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ChunkPack {
        ChunkPack::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "data",
                |m: &ChunkPack| { &m.data },
                |m: &mut ChunkPack| { &mut m.data },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "x",
                |m: &ChunkPack| { &m.x },
                |m: &mut ChunkPack| { &mut m.x },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "y",
                |m: &ChunkPack| { &m.y },
                |m: &mut ChunkPack| { &mut m.y },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "z",
                |m: &ChunkPack| { &m.z },
                |m: &mut ChunkPack| { &mut m.z },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<ChunkPack>(
                "ChunkPack",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static ChunkPack {
        static instance: ::protobuf::rt::LazyV2<ChunkPack> = ::protobuf::rt::LazyV2::INIT;
        instance.get(ChunkPack::new)
    }
}

impl ::protobuf::Clear for ChunkPack {
    fn clear(&mut self) {
        self.data.clear();
        self.x = 0;
        self.y = 0;
        self.z = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ChunkPack {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ChunkPack {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ChunkEntityPack {
    // message fields
    pub entity_pos: ::protobuf::RepeatedField<EntityPos>,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ChunkEntityPack {
    fn default() -> &'a ChunkEntityPack {
        <ChunkEntityPack as ::protobuf::Message>::default_instance()
    }
}

impl ChunkEntityPack {
    pub fn new() -> ChunkEntityPack {
        ::std::default::Default::default()
    }

    // repeated .EntityPos entity_pos = 1;


    pub fn get_entity_pos(&self) -> &[EntityPos] {
        &self.entity_pos
    }
    pub fn clear_entity_pos(&mut self) {
        self.entity_pos.clear();
    }

    // Param is passed by value, moved
    pub fn set_entity_pos(&mut self, v: ::protobuf::RepeatedField<EntityPos>) {
        self.entity_pos = v;
    }

    // Mutable pointer to the field.
    pub fn mut_entity_pos(&mut self) -> &mut ::protobuf::RepeatedField<EntityPos> {
        &mut self.entity_pos
    }

    // Take field
    pub fn take_entity_pos(&mut self) -> ::protobuf::RepeatedField<EntityPos> {
        ::std::mem::replace(&mut self.entity_pos, ::protobuf::RepeatedField::new())
    }

    // int32 x = 2;


    pub fn get_x(&self) -> i32 {
        self.x
    }
    pub fn clear_x(&mut self) {
        self.x = 0;
    }

    // Param is passed by value, moved
    pub fn set_x(&mut self, v: i32) {
        self.x = v;
    }

    // int32 y = 3;


    pub fn get_y(&self) -> i32 {
        self.y
    }
    pub fn clear_y(&mut self) {
        self.y = 0;
    }

    // Param is passed by value, moved
    pub fn set_y(&mut self, v: i32) {
        self.y = v;
    }

    // int32 z = 4;


    pub fn get_z(&self) -> i32 {
        self.z
    }
    pub fn clear_z(&mut self) {
        self.z = 0;
    }

    // Param is passed by value, moved
    pub fn set_z(&mut self, v: i32) {
        self.z = v;
    }
}

impl ::protobuf::Message for ChunkEntityPack {
    fn is_initialized(&self) -> bool {
        for v in &self.entity_pos {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.entity_pos)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.x = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.y = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.z = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.entity_pos {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        if self.x != 0 {
            my_size += ::protobuf::rt::value_size(2, self.x, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.y != 0 {
            my_size += ::protobuf::rt::value_size(3, self.y, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.z != 0 {
            my_size += ::protobuf::rt::value_size(4, self.z, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.entity_pos {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        if self.x != 0 {
            os.write_int32(2, self.x)?;
        }
        if self.y != 0 {
            os.write_int32(3, self.y)?;
        }
        if self.z != 0 {
            os.write_int32(4, self.z)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ChunkEntityPack {
        ChunkEntityPack::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<EntityPos>>(
                "entity_pos",
                |m: &ChunkEntityPack| { &m.entity_pos },
                |m: &mut ChunkEntityPack| { &mut m.entity_pos },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "x",
                |m: &ChunkEntityPack| { &m.x },
                |m: &mut ChunkEntityPack| { &mut m.x },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "y",
                |m: &ChunkEntityPack| { &m.y },
                |m: &mut ChunkEntityPack| { &mut m.y },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "z",
                |m: &ChunkEntityPack| { &m.z },
                |m: &mut ChunkEntityPack| { &mut m.z },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<ChunkEntityPack>(
                "ChunkEntityPack",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static ChunkEntityPack {
        static instance: ::protobuf::rt::LazyV2<ChunkEntityPack> = ::protobuf::rt::LazyV2::INIT;
        instance.get(ChunkEntityPack::new)
    }
}

impl ::protobuf::Clear for ChunkEntityPack {
    fn clear(&mut self) {
        self.entity_pos.clear();
        self.x = 0;
        self.y = 0;
        self.z = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ChunkEntityPack {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ChunkEntityPack {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum EntityType {
    T_Null = 0,
    T_Player = 1,
}

impl ::protobuf::ProtobufEnum for EntityType {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<EntityType> {
        match value {
            0 => ::std::option::Option::Some(EntityType::T_Null),
            1 => ::std::option::Option::Some(EntityType::T_Player),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [EntityType] = &[
            EntityType::T_Null,
            EntityType::T_Player,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            ::protobuf::reflect::EnumDescriptor::new_pb_name::<EntityType>("EntityType", file_descriptor_proto())
        })
    }
}

impl ::std::marker::Copy for EntityType {
}

impl ::std::default::Default for EntityType {
    fn default() -> Self {
        EntityType::T_Null
    }
}

impl ::protobuf::reflect::ProtobufValue for EntityType {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Enum(::protobuf::ProtobufEnum::descriptor(self))
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0ccommon.proto\"y\n\tEntityPos\x12\x1b\n\x01t\x18\x01\x20\x01(\x0e2\
    \x0b.EntityTypeR\x01tB\0\x12\x1d\n\tentity_id\x18\x02\x20\x01(\x05R\x08e\
    ntityIdB\0\x12\x0e\n\x01x\x18\x03\x20\x01(\x02R\x01xB\0\x12\x0e\n\x01y\
    \x18\x04\x20\x01(\x02R\x01yB\0\x12\x0e\n\x01z\x18\x05\x20\x01(\x02R\x01z\
    B\0:\0\".\n\x0bPlayerBasic\x12\x1d\n\tentity_id\x18\x01\x20\x01(\rR\x08e\
    ntityIdB\0:\0\"S\n\tChunkPack\x12\x14\n\x04data\x18\x01\x20\x01(\x0cR\
    \x04dataB\0\x12\x0e\n\x01x\x18\x02\x20\x01(\x05R\x01xB\0\x12\x0e\n\x01y\
    \x18\x03\x20\x01(\x05R\x01yB\0\x12\x0e\n\x01z\x18\x04\x20\x01(\x05R\x01z\
    B\0:\0\"p\n\x0fChunkEntityPack\x12+\n\nentity_pos\x18\x01\x20\x03(\x0b2\
    \n.EntityPosR\tentityPosB\0\x12\x0e\n\x01x\x18\x02\x20\x01(\x05R\x01xB\0\
    \x12\x0e\n\x01y\x18\x03\x20\x01(\x05R\x01yB\0\x12\x0e\n\x01z\x18\x04\x20\
    \x01(\x05R\x01zB\0:\0*(\n\nEntityType\x12\n\n\x06T_Null\x10\0\x12\x0c\n\
    \x08T_Player\x10\x01\x1a\0B\0b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
